config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'visitors#index'

  resources :questions do
    resources :answers
  end
  resources :tags, only: [:index]

  namespace :admin do
    root 'dashboard#index'
    resources :question
    resources :tags
  end

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/answer.rb
class Answer < ApplicationRecord
  paginates_per 3

  belongs_to :question, counter_cache: true
  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates_length_of :body, minimum: 30
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/concerns/has_friendly_id.rb
module HasFriendlyId
  extend ActiveSupport::Concern

  included do
    extend FriendlyId
    friendly_id :gen_slug, use: [:slugged, :finders]
  end

  private

  def gen_slug
    Array.new(16){ rand(36).to_s(36) }.join
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include HasFriendlyId

  has_many :answers, dependent: :destroy
  belongs_to :user

  acts_as_taggable_on :tags
  validates :title, :description, presence: true
  validates_length_of :title, minimum: 15, maximum: 150, :allow_blank => true
  validates_length_of :description, minimum: 30, :allow_blank => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable

  enum role: [:user, :admin]

  acts_as_tagger
  has_many :questions
  has_many :answers

  scope :non_admin, -> { where.not(:role => :admin) }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin!

  private
  def authenticate_admin!
    redirect_to root_path unless current_user.role == 'admin'
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < Admin::BaseController
    def index
      @users = User.non_admin.page(params[:page]).per(params[:per] || 10).eager_load(:questions)
    end
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::BaseController
    # CURD operation for Tags, which can be done by Admin/moderator only.
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :init_answer, only: [:new, :create, :update]
  before_action :get_question
  before_action :set_answer, except: [:index, :new, :create]

  def index
    @answers = @question.answers.page(params[:page])
    respond
  end

  def create
    @answer = @question.answers.build(answers_params.merge(user: current_user))
    @answer.save
    respond
  end

  def update
    @answer.update(answers_params)
    respond
  end

  def destroy
    @answer = @answer.destroy
    respond
  end

  private
  def get_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = @question.answers.find(params[:id])
  end

  def init_answer
    @answer_init = Answer.new
  end

  def answers_params
    params.require(:answer).permit(:body)
  end

  def respond
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, role: 'user'])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, except: [:index, :new, :create]
  before_action :init_answer, only: :show
  before_action :set_popular_tags, only: [:new, :create, :edit, :update]

  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def show
    @answers = @question.answers.page(params[:page] || 1)
  end

  def edit
    render 'new'
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description, tag_list: [])
  end

  def init_answer
    @answer = Answer.new
  end
  def set_popular_tags
    @popular_tags = ActsAsTaggableOn::Tag.most_used.limit(10)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.most_used.where("name LIKE (?)", "%#{params[:q]}%").limit(10)
    render json: @tags
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if current_user.role == 'user'
      redirect_to questions_path
    else
      redirect_to admin_root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.slim
.row
  .col-lg-8.offset-lg-2
    .card
      .card.card-outline-secondary
        - @users.each do |user|
          .card-header
            = user.name
          - user.questions.each do |question|
            .card-body.py-2
              .question
                h5
                  = link_to question.title, question
                p.mb-1.pl-2
                  = strip_tags(question.description).truncate(100)
                ul.tags
                  - question.tag_list.each do |tag|
                    li.tag
                      = tag

app/views/answers/_index.html.slim
= render partial: '/answers/show', collection: answers, as: :answer, locals: { question: question }
.mt-4
  = paginate answers

app/views/answers/_new.html.slim
.col-lg-12
  .pb-4
    h4 Add your Answer
    = render partial: '/shared/validation_messages', locals: {object: answer}
    = form_for [question, answer], remote: true do |f|
      div
        = f.cktext_area :body, ckeditor: { language: 'uk'}
      div.mt-3.text-right
        = f.submit 'Add Answer', class: 'btn btn-primary'

app/views/answers/_show.html.slim
div(id="answer_#{answer.id}")
  .answer.body
    = h answer.body.html_safe
    .row
      .col-md-8
        - if answer.user == current_user
          = link_to "Edit", edit_question_answer_path(question, answer), remote: true
          | &nbsp;|&nbsp;
          = link_to "Delete", question_answer_path(question, answer), method: :delete, remote: true, data: {confirm: "Are you sure?"}
      .col-md-4
        .post-details
          div
            | Answered&nbsp;
            = time_ago_in_words(answer.created_at)
            | &nbsp;Ago
          div
            | By&nbsp;
            = answer.user.name

app/views/answers/create.js.erb
<% if @answer.id %>
  $("#answers").prepend("<%= escape_javascript(render partial: '/answers/show', locals: { answer: @answer, question: @question } )%>");
  $("#add-answer").html("<%= escape_javascript(render partial: '/answers/new', locals: { answer: @answer_init, question: @question }) %>");
<% else %>
  $("#add-answer").html("<%= escape_javascript(render partial: '/answers/new', locals: { answer: @answer, question: @question }) %>");
<% end %>

app/views/answers/destroy.js.erb
$("#answer_<%= @answer.id %>").remove()

app/views/answers/edit.js.erb
$("#answer_<%= @answer.id %>").html("<%= escape_javascript(render partial: '/answers/new', locals: { answer: @answer, question: @question }) %>");
$("#add-answer").hide();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $("#answer_<%= @answer.id %>").html("<%= escape_javascript(render partial: '/answers/new', locals: { answer: @answer, question: @question }) %>");
<% else %>
  $("#answer_<%= @answer.id %>").html("<%= escape_javascript(render partial: '/answers/show', locals: { answer: @answer, question: @question } )%>");
  $("#add-answer").show();
  $("#add-answer").html("<%= escape_javascript(render partial: '/answers/new', locals: { answer: @answer_init, question: @question }) %>");
<% end %>

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    a.navbar-brand href="#" Sample Stackoverflow
    button.navbar-toggler aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        - if current_user
          - if  current_user.role == 'user'
            li.nav-item(class="#{'active' if params[:action] == 'index'}")
              = link_to "Question", questions_path, class: "nav-link"
              a.nav-link href="#"
            li.nav-item(class="#{'active' if params[:action] == 'new' && params[:controller] == 'questions'}")
              = link_to "Add Question", new_question_path, class: "nav-link"
          li.nav-item
            = link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SampleStackoverflow
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: "layouts/navbar"
    .container-fluid
      .my-5
        = yield

app/views/questions/index.html.slim
.row
  .col-lg-8.offset-lg-2
    .card
      .card.card-outline-secondary
        .card-header
          h2 All Question
        .card-body
          - @questions.each do |question|
            .question
              h5
                = link_to question.title, question
              p.mb-1.pl-2
                = strip_tags(question.description).truncate(100)
              ul.tags
                - question.tag_list.each do |tag|
                  li.tag
                    = tag

app/views/questions/new.html.slim
= javascript_include_tag Ckeditor.cdn_url

.row
  .col-lg-8.offset-lg-2
    h2 Add Question
    = render partial: '/shared/validation_messages', locals: { object: @question }

    = form_for @question do |f|
      .input-group.mb-3
        .input-group-prepend
          = f.label :title, class: "input-group-text"
        = f.text_field :title, class: 'form-control'
      div
        = f.cktext_area :description, ckeditor: { language: 'uk'}
      div.mt-2
        .input-group.mb-3
          = f.label :tags
          = f.select :tag_list, @popular_tags.map(&:name), {}, multiple: true, class: "chosen-select form-control"
      div.mt-3.text-right
        = f.submit 'Add Your Question', class: 'btn btn-primary'

app/views/questions/show.html.slim
= javascript_include_tag Ckeditor.cdn_url

.row
  .col-lg-8.offset-lg-2
    .card
      .card.card-outline-secondary
        .card-header
          h3
            = @question.title
        .card-body
          .body
            = h @question.description.html_safe
          .row.mt-4
            .col-md-8
              ul.tags
                - @question.tag_list.each do |tag|
                  li.tag
                    = tag
              div
                - if @question.user == current_user
                  = link_to "Edit", edit_question_path(@question) 
                  | &nbsp;|&nbsp;
                  = link_to "Delete", question_path(@question), method: :delete, data: {confirm: "Are you sure?"}
            .col-md-4
              .post-details
                div
                  | Asked&nbsp;
                  = time_ago_in_words(@question.created_at)
                  | &nbsp;Ago
                div
                  | By&nbsp;
                  = @question.user.name

        .card.card-outline-secondary
          .card-header
            h3
              - if @question.answers.present?
                = @question.answers_count
                | &nbsp;Answer(s)
              - else
               | No answers yet
          #answers.card-body
            = render partial: '/answers/index', locals: { answers: @answers, question: @question }
      .card.card-outline-secondary
        #add-answer.mt-4
          = render partial: '/answers/new', locals: { answer: @answer, question: @question }

app/views/shared/_validation_messages.html.slim
.validation.text-danger
  - if object.errors.full_messages.any?
    ul
      - object.errors.full_messages.each do |error_message|
        li
          = error_message